
#ifndef _MSAB_PROF_H_
#define _MSAB_PROF_H_

// #define MA_PROF_CONST_STORAGESIZE 44040192
// #define MA_PROF_CONST_SCREENSIZE_Y 320
// #define MA_PROF_CONST_SCREENSIZE_X 240
// #define MA_PROF_CONST_MAXJARSIZE DYNAMIC
// #define MA_PROF_CONST_HEAPSIZE DYNAMIC
// #define MA_PROF_CONST_BITSPERPIXEL 8
// #define MA_PROF_SUPPORT_JAVAPACKAGE_BLUETOOTH

#endif /* _MSAB_PROF_H_ */
