#!/bin/sh
curr_dir=$(pwd)
script_dir=$(echo $0 | sed 's/convert//')

# Try to resolve full path to script
if [ -e $curr_dir/$0 ]; then
	script=$curr_dir/$0
else
	script=$0
fi

cd $script_dir
DYLD_LIBRARY_PATH=$(pwd) ./convertb $*
cd $curr_dir
