/* This file was generated. */

char VIRTUAL_KEYBOARD_DEFAULT_XML[] =
"<layouts format=\"1.0\">"
"  <layout name=\"DEFAULT\">"
"    <row>"
"      <key label=\"q\" output=\"q\">"
"      </key>"
"      <key label=\"w\" output=\"w\">"
"      </key>"
"      <key label=\"e\" output=\"e\">"
"      </key>"
"      <key label=\"r\" output=\"r\">"
"      </key>"
"      <key label=\"t\" output=\"t\">"
"      </key>"
"      <key label=\"y\" output=\"y\">"
"      </key>"
"      <key label=\"u\" output=\"u\">"
"      </key>"
"      <key label=\"i\" output=\"i\">"
"      </key>"
"      <key label=\"o\" output=\"o\">"
"      </key>"
"      <key label=\"p\" output=\"p\">"
"      </key>"
"    </row>"
"	<row>"
"      <key label=\"a\" output=\"a\">"
"      </key>"
"      <key label=\"s\" output=\"s\">"
"      </key>"
"      <key label=\"d\" output=\"d\">"
"      </key>"
"      <key label=\"f\" output=\"f\">"
"      </key>"
"      <key label=\"g\" output=\"g\">"
"      </key>"
"      <key label=\"h\" output=\"h\">"
"      </key>"
"      <key label=\"j\" output=\"j\">"
"      </key>"
"      <key label=\"k\" output=\"k\">"
"      </key>"
"      <key label=\"l\" output=\"l\">"
"      </key>"
"    </row>"
"	<row>"
"	  <key label=\"^\" output=\"\" onclick=\"shift\">"
"	  </key>"
"      <key label=\"z\" output=\"z\">"
"      </key>"
"      <key label=\"x\" output=\"x\">"
"      </key>"
"      <key label=\"c\" output=\"c\">"
"      </key>"
"      <key label=\"v\" output=\"v\">"
"      </key>"
"      <key label=\"b\" output=\"b\">"
"      </key>"
"      <key label=\"n\" output=\"n\">"
"      </key>"
"      <key label=\"m\" output=\"m\">"
"      </key>"
"      <key label=\"<\" output=\"\" onclick=\"remove\">"
"      </key>"
"    </row>"
"    <row>"
"	  <key onclick=\"left\" label=\"<-\">"
"	  </key>"
"	  <key onclick=\"hide\" label=\"-\">"
"	  </key>"
"	  <key label=\",\" output=\",\">"
"	  </key>"
"	  <key label=\"\" width=\"3\" output=\" \">"
"	  </key>"
"	  <key label=\".\" output=\".\">"
"	  </key>"
"	  <key change=\"NUMBERS\" label=\"12\">"
"	  </key>"
"	  <key label=\"\\n\" output=\"\" onclick=\"line\">"
"	  </key>"
"	  <key onclick=\"right\" label=\"->\">"
"	  </key>"
"   </row>"
"  </layout>"
"  <layout name=\"NUMBERS\">"
"  	<row>"
"		<key label=\"1\" output=\"1\">"
"		</key>"
"		<key label=\"2\" output=\"2\">"
"		</key>"
"		<key label=\"3\" output=\"3\">"
"		</key>"
"		<key label=\"4\" output=\"4\">"
"		</key>"
"		<key label=\"5\" output=\"5\">"
"		</key>"
"		<key label=\"6\" output=\"6\">"
"		</key>"
"		<key label=\"7\" output=\"7\">"
"		</key>"
"		<key label=\"8\" output=\"8\">"
"		</key>"
"		<key label=\"9\" output=\"9\">"
"		</key>"
"		<key label=\"0\" output=\"0\">"
"		</key>"
"	</row>"
"  	<row>"
"  		<key label=\"!\" output=\"!\">"
"  		</key>"
"  		<key label=\"@\" output=\"@\">"
"  		</key>"
"  		<key label=\"#\" output=\"#\">"
"  		</key>"
"  		<key label=\"$\" output=\"$\">"
"  		</key>"
"  		<key label=\"%\" output=\"%\">"
"  		</key>"
"  		<key label=\"&\" output=\"&\">"
"  		</key>"
"  		<key label=\"*\" output=\"*\">"
"  		</key>"
"  		<key label=\"?\" output=\"?\">"
"  		</key>"
"  		<key label=\"/\" output=\"/\">"
"  		</key>"
"  		<key label=\":\" output=\":\">"
"  		</key>"
"  	</row>"
"  	<row>"
"  		<key label=\"_\" output=\"_\">"
"  		</key>"
"  		<key label=\"'\" output=\"'\">"
"  		</key>"
"  		<key label=\"(\" output=\"(\">"
"  		</key>"
"  		<key label=\")\" output=\")\">"
"  		</key>"
"  		<key label=\"-\" output=\"-\">"
"  		</key>"
"  		<key label=\"+\" output=\"+\">"
"  		</key>"
"  		<key label=\";\" output=\";\">"
"  		</key>"
"  		<key label=\",\" output=\",\">"
"  		</key>"
"  	</row>"
"   <row>"
"	  <key onclick=\"hide\" label=\"-\">"
"	  </key>"
"	  <key label=\",\" output=\",\">"
"	  </key>"
"	  <key label=\"\" width=\"3\" output=\" \">"
"	  </key>"
"	  <key label=\".\" output=\".\">"
"	  </key>"
"	  <key change=\"DEFAULT\" label=\"ab\">"
"	  </key>"
"	  <key label=\"\\n\" output=\"\" onclick=\"line\">"
"	  </key>"
"    </row>"
"  </layout>"
"<layouts>\0";
