/**
* The available widget properties for a #MAW_CHECK_BOX. See \ref WidgetProperties "Widget properties" for more properties.
*/
group WidgetCheckBoxProperties "Check box" {
	constset MAString MAW_CHECK_BOX_ {
		/**
		* @brief Set or get the checked state of the checkbox.
		*
		* @validvalue A boolean string 'true' or 'false'.
		*
		* @par Example
		* \code
		*	maWidgetSetProperty(checkBoxHandle, MAW_CHECK_BOX_CHECKED, "true");
		* \endcode
		*/
		CHECKED = "checked";
	}
} // end of WidgetCheckBoxProperties
