



#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 33
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
* if you want the limit (max/min) macros for int types. 
*/
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef _MSC_VER
#include <io.h>
#define isatty _isatty
#endif

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
* integer for use as an array index.  If the signed char is negative,
* we want to instead treat it as an 8-bit unsigned char, hence the
* double cast.
*/
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
* but we do it the disgusting crufty way forced on us by the ()-less
* definition of BEGIN.
*/
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
* to BEGIN to return to the state.  The YYSTATE alias is for lex
* compatibility.
*/
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
*/
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
*       access to the local variable yy_act. Since yyless() is a macro, it would break
*       existing scanners that call yyless() from OUTSIDE yylex. 
*       One obvious solution it to make yy_act a global. I tried that, and saw
*       a 5% performance hit in a non-yylineno scanner, because yy_act is
*       normally declared as a register variable-- so it is not worth it.
*/
#define  YY_LESS_LINENO(n) \
	do { \
	int yyl;\
	for ( yyl = n; yyl < yyleng; ++yyl )\
	if ( yytext[yyl] == '\n' )\
	--yylineno;\
	}while(0)

/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
{ \
	/* Undo effects of setting up yytext. */ \
	int yyless_macro_arg = (n); \
	YY_LESS_LINENO(yyless_macro_arg);\
	*yy_cp = (yy_hold_char); \
	YY_RESTORE_YY_MORE_OFFSET \
	(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
	YY_DO_BEFORE_ACTION; /* set up yytext again */ \
} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

/* The following is because we cannot portably get our hands on size_t
* (without autoconf's help, which isn't available because we want
* flex-generated scanners to compile on their own).
*/

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	* characters.
	*/
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	* characters.
	*/
	size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	* and can realloc() it to grow it, and should free() it to
	* delete it.
	*/
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	* if we're using stdio for input, then we want to use getc()
	* instead of fread(), to make sure we stop fetching input after
	* each newline.
	*/
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	* If so, '^' rules will be active on the next match, otherwise
	* not.
	*/
	int yy_at_bol;

	int yy_bs_lineno; /**< The line count. */
	int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	* end of it.
	*/
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	* then we mark the buffer as YY_EOF_PENDING, to indicate that we
	* shouldn't try reading from the input source any more.  We might
	* still have a bunch of tokens to match, though, because of
	* possible backing-up.
	*
	* When we actually see the EOF, we change the status to "new"
	* (via yyrestart()), so that the user can continue scanning by
	* just pointing yyin at a new input file.
	*/
#define YY_BUFFER_EOF_PENDING 2

};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
* future we want to put the buffer states in a more general
* "scanner state".
*
* Returns the top of the stack, or NULL.
*/
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
	? (yy_buffer_stack)[(yy_buffer_stack_top)] \
	: NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
* NULL or when we need an lvalue. For internal use only.
*/
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
* instead of setting up a fresh yyin.  A bit of a hack ...
*/
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
{ \
	if ( ! YY_CURRENT_BUFFER ){ \
	yyensure_buffer_stack (); \
	YY_CURRENT_BUFFER_LVALUE =    \
	yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
}

#define yy_set_bol(at_bol) \
{ \
	if ( ! YY_CURRENT_BUFFER ){\
	yyensure_buffer_stack (); \
	YY_CURRENT_BUFFER_LVALUE =    \
	yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

#define yywrap() 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
* corresponding action - sets up yytext.
*/
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 65
#define YY_END_OF_BUFFER 66
/* This struct is not used in this scanner,
but its presence is necessary. */
struct yy_trans_info
{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
};
static yyconst flex_int16_t yy_accept[199] =
{   0,
0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
66,   64,   55,   55,   30,   31,   63,   63,   63,   42,
42,   41,   41,   41,   41,   41,   41,   41,   41,   41,
41,   41,   41,   41,   41,   41,   64,   40,   37,   38,
39,   40,   64,   55,   55,   64,   64,   58,   57,   62,
61,   62,    0,   59,   56,    0,   42,    0,    0,   41,
41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
41,    0,   36,   32,   33,   35,   34,    0,    0,   51,
0,   59,   56,   60,    0,    0,   46,   48,   43,   13,

41,   41,   41,   41,   41,   29,   41,   41,   41,   41,
41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
41,    0,   52,    0,    0,   47,   49,    0,   41,   14,
17,   41,   41,   11,   41,   26,   41,   41,   18,   41,
5,   41,   41,   41,   41,   41,   20,    3,    4,   16,
12,    0,   53,    0,   54,    0,    0,   44,   15,   41,
41,   41,   27,   10,   21,   41,   41,   41,   41,   41,
41,   22,   50,    0,    0,   45,   41,   19,    9,   41,
23,    7,   41,   28,    1,    8,   24,   41,   25,   41,
41,    2,   41,   41,   41,   41,    6,    0

} ;

static yyconst flex_int32_t yy_ec[256] =
{   0,
1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
1,    4,    1,    5,    6,    1,    1,    1,    7,    8,
8,    9,    8,    8,   10,   11,   12,   13,   14,   15,
16,   17,   17,   18,   17,   19,   17,    1,    8,    8,
8,    8,    1,    1,   20,   21,   22,   23,   24,   25,
26,   27,   28,   29,   30,   31,   32,   33,   34,   29,
29,   35,   36,   37,   38,   29,   39,   40,   41,   29,
8,   42,    8,    1,   43,    1,   44,   45,   44,   44,

46,   45,   47,   47,   47,   47,   47,   47,   48,   49,
47,   47,   47,   50,   47,   50,   51,   50,   47,   52,
47,   47,    8,    8,    8,    1,    1,    1,    1,    1,
1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
1,    1,    1,    1,    1
} ;

static yyconst flex_int32_t yy_meta[53] =
{   0,
1,    1,    1,    2,    1,    1,    1,    1,    1,    1,
3,    1,    4,    4,    4,    4,    4,    4,    4,    5,
5,    5,    5,    6,    5,    7,    7,    7,    7,    7,
7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
7,    1,    7,    5,    5,    6,    7,    7,    7,    7,
7,    8
} ;

static yyconst flex_int16_t yy_base[211] =
{   0,
0,  369,   50,   51,   57,   61,  371,  370,   65,   67,
372,  376,  376,  376,  376,  376,  376,   64,   63,   60,
74,    0,   48,  344,  336,  336,  337,   63,  347,  341,
341,   64,  340,  335,  328,  312,  356,  376,  376,  376,
376,  104,  354,  353,  352,   92,  105,  376,  376,  376,
376,  344,   79,  376,  376,  114,    0,  121,    0,    0,
330,  317,  333,  314,  313,  316,  316,  315,  319,   80,
322,  313,  319,  307,  311,  306,  304,  299,  315,  302,
285,  142,  376,  376,  376,  376,  376,  330,  112,  376,
104,  329,  328,  376,  149,  156,   97,  163,    0,  128,

308,  296,  309,  297,  307,    0,  297,  293,  305,  298,
283,  298,  285,  286,  291,  280,  280,  279,  107,  292,
266,  309,  376,  141,  147,  159,  171,  178,  294,    0,
0,  291,  279,    0,  289,    0,  278,  276,    0,  269,
0,  281,  266,  270,  280,  277,  184,    0,    0,    0,
0,  295,  376,  283,  376,  282,  193,  200,    0,  275,
272,  264,    0,    0,  185,  257,  257,  259,  249,  248,
245,    0,  376,  258,  199,  207,  164,    0,    0,  182,
0,    0,  130,    0,    0,    0,    0,  124,    0,  117,
89,    0,   65,   68,   64,   30,    0,  376,  226,  234,

242,  250,  256,  261,  269,  275,  278,  281,  286,  287
} ;

static yyconst flex_int16_t yy_def[211] =
{   0,
198,    1,  199,  199,  200,  200,  201,  201,  202,  202,
198,  198,  198,  198,  198,  198,  198,  198,  198,  203,
203,  204,  204,  204,  204,  204,  204,  204,  204,  204,
204,  204,  204,  204,  204,  204,  198,  198,  198,  198,
198,  198,  205,  205,  205,  198,  205,  198,  198,  198,
198,  198,  206,  198,  198,  198,   21,  198,  207,  204,
204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
204,  198,  198,  198,  198,  198,  198,  205,  198,  198,
198,  205,  205,  198,  198,  198,  208,  198,  207,  204,

204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
204,  209,  198,  198,  198,  210,  198,  198,  204,  204,
204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
204,  198,  198,  198,  198,  198,  198,  198,  204,  204,
204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
204,  204,  198,  198,  198,  198,  204,  204,  204,  204,
204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
204,  204,  204,  204,  204,  204,  204,    0,  198,  198,

198,  198,  198,  198,  198,  198,  198,  198,  198,  198
} ;

static yyconst flex_int16_t yy_nxt[429] =
{   0,
12,   13,   14,   13,   15,   12,   16,   17,   17,   18,
17,   19,   20,   21,   21,   21,   21,   21,   21,   22,
23,   24,   25,   26,   22,   27,   22,   22,   22,   22,
28,   22,   29,   30,   31,   32,   33,   34,   35,   22,
22,   12,   12,   22,   22,   36,   22,   22,   22,   22,
22,   22,   39,   39,   40,   40,   41,   41,   44,   45,
44,   46,   44,   45,   44,   46,  197,   51,   47,   51,
56,   54,   47,   52,   55,   52,   53,   53,   53,   53,
53,   53,   53,   58,   56,   61,   67,  196,   62,   95,
68,   42,   42,   69,   90,   91,   70,   58,   75,   71,

76,  109,   96,  195,   77,   58,   83,  194,   84,   89,
85,   59,  110,   92,  123,   91,   93,  124,  125,   58,
128,  148,  149,  193,   96,  198,   97,   97,   97,   97,
97,   97,   97,   98,   98,   98,   98,   98,   98,   98,
192,  129,  128,  153,  154,   86,  130,  191,   87,  155,
156,  190,   87,   87,  122,  122,  122,  122,  122,  122,
122,  126,  126,  126,  126,  126,  126,  126,  127,  127,
127,  127,  127,  127,  127,   98,   98,   98,   98,   98,
98,   98,  157,  127,  127,  127,  127,  127,  127,  127,
158,  158,  158,  158,  158,  158,  158,  171,  180,  189,

188,  155,  172,  181,  157,  176,  176,  176,  176,  176,
176,  176,  158,  158,  158,  158,  158,  158,  158,  176,
176,  176,  176,  176,  176,  176,   38,   38,   38,   38,
38,   38,   38,   38,   43,   43,   43,   43,   43,   43,
43,   43,   48,   48,   48,   48,   48,   48,   48,   48,
50,   50,   50,   50,   50,   50,   50,   50,   57,   57,
153,   57,  187,   57,   60,   60,   60,   60,   60,   88,
88,   88,   88,   88,   88,   88,   88,   53,   53,  186,
53,   99,   99,   99,   97,  185,   97,  122,  184,  122,
126,  183,  126,  182,  179,  178,  177,  175,  174,  173,

170,  169,  168,  167,  166,  165,  164,  163,  162,  161,
160,  159,  152,  151,  150,  147,  146,  145,  144,  143,
142,  141,  140,  139,  138,  137,  136,  135,  134,  133,
132,  131,   89,   89,   89,  121,  120,  119,  118,  117,
116,  115,  114,  113,  112,  111,  108,  107,  106,  105,
104,  103,  102,  101,  100,   94,   89,   89,   89,   82,
81,   80,   79,   78,   74,   73,   72,   66,   65,   64,
63,  198,   49,   49,   37,   11,  198,  198,  198,  198,
198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
198,  198,  198,  198,  198,  198,  198,  198,  198,  198,

198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
198,  198,  198,  198,  198,  198,  198,  198
} ;

static yyconst flex_int16_t yy_chk[429] =
{   0,
1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
1,    1,    3,    4,    3,    4,    3,    4,    5,    5,
5,    5,    6,    6,    6,    6,  196,    9,    5,   10,
20,   19,    6,    9,   19,   10,   18,   18,   18,   18,
18,   18,   18,   20,   21,   23,   28,  195,   23,   53,
28,    3,    4,   28,   46,   46,   28,   21,   32,   28,

32,   70,   53,  194,   32,   20,   42,  193,   42,   47,
42,   20,   70,   47,   89,   89,   47,   91,   91,   21,
97,  119,  119,  191,   53,   21,   56,   56,   56,   56,
56,   56,   56,   58,   58,   58,   58,   58,   58,   58,
190,  100,   97,  124,  124,   42,  100,  188,   42,  125,
125,  183,   42,   42,   82,   82,   82,   82,   82,   82,
82,   95,   95,   95,   95,   95,   95,   95,   96,   96,
96,   96,   96,   96,   96,   98,   98,   98,   98,   98,
98,   98,  126,  127,  127,  127,  127,  127,  127,  127,
128,  128,  128,  128,  128,  128,  128,  147,  165,  180,

177,  175,  147,  165,  126,  157,  157,  157,  157,  157,
157,  157,  158,  158,  158,  158,  158,  158,  158,  176,
176,  176,  176,  176,  176,  176,  199,  199,  199,  199,
199,  199,  199,  199,  200,  200,  200,  200,  200,  200,
200,  200,  201,  201,  201,  201,  201,  201,  201,  201,
202,  202,  202,  202,  202,  202,  202,  202,  203,  203,
174,  203,  171,  203,  204,  204,  204,  204,  204,  205,
205,  205,  205,  205,  205,  205,  205,  206,  206,  170,
206,  207,  207,  207,  208,  169,  208,  209,  168,  209,
210,  167,  210,  166,  162,  161,  160,  156,  154,  152,

146,  145,  144,  143,  142,  140,  138,  137,  135,  133,
132,  129,  122,  121,  120,  118,  117,  116,  115,  114,
113,  112,  111,  110,  109,  108,  107,  105,  104,  103,
102,  101,   93,   92,   88,   81,   80,   79,   78,   77,
76,   75,   74,   73,   72,   71,   69,   68,   67,   66,
65,   64,   63,   62,   61,   52,   45,   44,   43,   37,
36,   35,   34,   33,   31,   30,   29,   27,   26,   25,
24,   11,    8,    7,    2,  198,  198,  198,  198,  198,
198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
198,  198,  198,  198,  198,  198,  198,  198,  198,  198,

198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
198,  198,  198,  198,  198,  198,  198,  198
} ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[66] =
{   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 
0, 1, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
* any uses of REJECT which flex missed.
*/
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;


// RCOMPL.CPP
// Generated from RCOMP.L
//
// Copyright (c) 1997-1999 Symbian Ltd.  All rights reserved.
//

#include <limits.h>
#include "structst.h"
//#include "rcompl.hpp"
#include "rcomp.hpp"
#include "fileline.h"

void yyerror(const char* msg, ...);

#define VALUE_LEN   1024	// must match sizeof(YYSTYPE.Value)
char buf[VALUE_LEN];
char * pCh;
#define CHECK_APPEND(x)	\
	if (pCh-buf==VALUE_LEN-1) { yyerror("string too long - %c ignored", (x)); } else {*pCh++ = (x); }

int isCharLiteral;

//YYSTYPE yylval;

extern String		InputBaseName;
extern FileLineManager* pFileLineHandler;
extern int*		pCurrentLineNumber;
char RealLineNumber[200];







#define INITIAL 0
#define string_rules 1
#define file_line_rules 2
#define cpp_comment 3
#define c_comment 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
* down here because we want the user's section 1 to have been scanned first.
* The user has a chance to override it with an option.
*/
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Macros after this point can all be overridden by user definitions in
* section 1.
*/

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

static void yyunput (int c,char *buf_ptr  );

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
* we now use fwrite().
*/
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
* is returned in "result".
*/
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
{ \
	int c = '*'; \
	int n; \
	for ( n = 0; n < max_size && \
	(c = getc( yyin )) != EOF && c != '\n'; ++n ) \
	buf[n] = (char) c; \
	if ( c == '\n' ) \
	buf[n++] = (char) c; \
	if ( c == EOF && ferror( yyin ) ) \
	YY_FATAL_ERROR( "input in flex scanner failed" ); \
	result = n; \
} \
	else \
{ \
	errno=0; \
	while ( (result = (int)fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
{ \
	if( errno != EINTR) \
{ \
	YY_FATAL_ERROR( "input in flex scanner failed" ); \
	break; \
} \
	errno=0; \
	clearerr(yyin); \
} \
}\
	\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
* we don't want an extra ';' after the "return" because that will cause
* some compilers to complain about unreachable statements.
*/
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
* easily add parameters.
*/
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
* have been set up.
*/
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
	(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
*/
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;







	if ( !(yy_init) )
	{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
	}

	while ( 1 )		/* loops until end-of-file is reached */
	{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		* the current run.
		*/
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
		{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
			{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
			}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 199 )
					yy_c = yy_meta[(unsigned int) yy_c];
			}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
		}
		while ( yy_base[yy_current_state] != 376 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
		{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
		}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
		{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )

					yylineno++;
			;
		}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
		{ /* beginning of action switch */
		case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

		case 1:
			YY_RULE_SETUP

				return L_STRUCT;
			YY_BREAK
		case 2:
			YY_RULE_SETUP

				return L_RESOURCE;
			YY_BREAK
		case 3:
			YY_RULE_SETUP

				return L_UID2;
			YY_BREAK
		case 4:
			YY_RULE_SETUP

				return L_UID3;
			YY_BREAK
		case 5:
			YY_RULE_SETUP

				return L_NAME;
			YY_BREAK
		case 6:
			YY_RULE_SETUP

				return L_CHARACTER_SET;
			YY_BREAK
		case 7:
			YY_RULE_SETUP

				return L_OFFSET;
			YY_BREAK
		case 8:
			YY_RULE_SETUP

				return L_SYSTEM;
			YY_BREAK
		case 9:
			YY_RULE_SETUP

				return L_GLOBAL;
			YY_BREAK
		case 10:
			YY_RULE_SETUP

				return L_LOCAL;
			YY_BREAK
		case 11:
			YY_RULE_SETUP

				return L_ENUM;
			YY_BREAK
		case 12:
			YY_RULE_SETUP

				return L_ENUM;
			YY_BREAK
		case 13:
			YY_RULE_SETUP

				return L_BUF;
			YY_BREAK
		case 14:
			YY_RULE_SETUP

				return L_BUF8;
			YY_BREAK
		case 15:
			YY_RULE_SETUP

				return L_BUF16;
			YY_BREAK
		case 16:
			YY_RULE_SETUP

				return L_WORD;
			YY_BREAK
		case 17:
			YY_RULE_SETUP

				return L_BYTE;
			YY_BREAK
		case 18:
			YY_RULE_SETUP

				return L_LONG;
			YY_BREAK
		case 19:
			YY_RULE_SETUP

				return L_DOUBLE;
			YY_BREAK
		case 20:
			YY_RULE_SETUP

				return L_TEXT;
			YY_BREAK
		case 21:
			YY_RULE_SETUP

				return L_LTEXT;
			YY_BREAK
		case 22:
			YY_RULE_SETUP

				return L_TEXT8;
			YY_BREAK
		case 23:
			YY_RULE_SETUP

				return L_LTEXT8;
			YY_BREAK
		case 24:
			YY_RULE_SETUP

				return L_TEXT16;
			YY_BREAK
		case 25:
			YY_RULE_SETUP

				return L_LTEXT16;
			YY_BREAK
		case 26:
			YY_RULE_SETUP

				return L_LINK;
			YY_BREAK
		case 27:
			YY_RULE_SETUP

				return L_LLINK;
			YY_BREAK
		case 28:
			YY_RULE_SETUP

				return L_SRLINK;
			YY_BREAK
		case 29:
			YY_RULE_SETUP

				return L_LEN;
			YY_BREAK
		case 30:
			YY_RULE_SETUP

			{ BEGIN(string_rules); pCh = buf; isCharLiteral=0; }
			YY_BREAK
		case 31:
			YY_RULE_SETUP

			{ BEGIN(string_rules); pCh = buf; isCharLiteral=1; }
			YY_BREAK
		case 32:
			YY_RULE_SETUP

			{ CHECK_APPEND('"'); }
			YY_BREAK
		case 33:
			YY_RULE_SETUP

			{ CHECK_APPEND('\''); };
			YY_BREAK
		case 34:
			YY_RULE_SETUP

			{ CHECK_APPEND( * ( strchr("\rr\bb\ff\nn\tt\vv\aa", yytext[1])-1));}
			YY_BREAK
		case 35:
			YY_RULE_SETUP

			{ CHECK_APPEND('\\'); }
			YY_BREAK
		case 36:
			/* rule 36 can match eol */
			YY_RULE_SETUP

				/* Escaped newline ignored*/ ;
			YY_BREAK
		case 37:
			/* rule 37 can match eol */
			YY_RULE_SETUP

			{ yyerror( isCharLiteral?"Unterminated character literal":"Unterminated string"); BEGIN 0; }
			YY_BREAK
		case 38:
			YY_RULE_SETUP

			{ 
				if (!isCharLiteral) 
				{
					*pCh = '\0'; BEGIN(0); strcpy( yylval.Value, buf); return L_STRING_LITERAL;
				}
				CHECK_APPEND(*yytext);
			}
			YY_BREAK
		case 39:
			YY_RULE_SETUP

			{ 
				if (isCharLiteral) 
				{
					*pCh = '\0'; BEGIN(0); strcpy( yylval.Value, buf); return L_CHAR_LITERAL;
				}
				CHECK_APPEND(*yytext);
			}
			YY_BREAK
		case 40:
			YY_RULE_SETUP

			{ CHECK_APPEND(*yytext); }
			YY_BREAK
		case 41:
			YY_RULE_SETUP

			{	
				BEGIN(0);
				strcpy( yylval.Value, yytext);
				return L_LABEL;
			}
			YY_BREAK
		case 42:
			YY_RULE_SETUP

			{	strcpy( yylval.Value, yytext); return L_NUM_NATURAL; }
			YY_BREAK
		case 43:
			YY_RULE_SETUP

			{	strcpy( yylval.Value, yytext); return L_NUM_NATURAL; }
			YY_BREAK
		case 44:
			YY_RULE_SETUP

			{	strcpy( yylval.Value, yytext); return L_NUM_FLOAT;}
			YY_BREAK
		case 45:
			YY_RULE_SETUP

			{	strcpy( yylval.Value, yytext); return L_NUM_FLOAT;}
			YY_BREAK
		case 46:
			YY_RULE_SETUP

			{	strcpy( yylval.Value, yytext); return L_NUM_FLOAT;}
			YY_BREAK
		case 47:
			YY_RULE_SETUP

			{	strcpy( yylval.Value, yytext); return L_NUM_FLOAT;}
			YY_BREAK
		case 48:
			YY_RULE_SETUP

			{	strcpy( yylval.Value, yytext); return L_NUM_FLOAT;}
			YY_BREAK
		case 49:
			YY_RULE_SETUP

			{	strcpy( yylval.Value, yytext); return L_NUM_FLOAT;}
			YY_BREAK
		case 50:
			YY_RULE_SETUP

			{	BEGIN( file_line_rules); strcpy( RealLineNumber, yytext+2); }
			YY_BREAK
		case 51:
			*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
			(yy_c_buf_p) = yy_cp -= 1;
			YY_DO_BEFORE_ACTION; /* set up yytext again */
			YY_RULE_SETUP

			{	BEGIN(0); // # <line> "" means start of base file.
			pFileLineHandler->SetBase( InputBaseName, * pCurrentLineNumber);
			}
			YY_BREAK
		case 52:
			/* rule 52 can match eol */
			*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
			(yy_c_buf_p) = yy_cp -= 1;
			YY_DO_BEFORE_ACTION; /* set up yytext again */
			YY_RULE_SETUP

			{	BEGIN(0); // # <line> <filename> means start of named base file.
			pFileLineHandler->SetInclude( yytext, * pCurrentLineNumber);
			}
			YY_BREAK
		case 53:
			/* rule 53 can match eol */
			*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
			(yy_c_buf_p) = yy_cp -= 1;
			YY_DO_BEFORE_ACTION; /* set up yytext again */
			YY_RULE_SETUP

			{
				BEGIN(0); // # <line> <filename> 1 means start of an included file.
				pFileLineHandler->SetInclude( yytext, * pCurrentLineNumber);
			}
			YY_BREAK
		case 54:
			/* rule 54 can match eol */
			*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
			(yy_c_buf_p) = yy_cp -= 1;
			YY_DO_BEFORE_ACTION; /* set up yytext again */
			YY_RULE_SETUP

			{
				BEGIN(0); // # <line> <filename> 2 means end of an included file and now at <line> in <filename>.
				pFileLineHandler->PostInclude( yytext, RealLineNumber, * pCurrentLineNumber);
			}
			YY_BREAK
		case 55:
			/* rule 55 can match eol */
			YY_RULE_SETUP

				; // skipped
			YY_BREAK
		case 56:
			YY_RULE_SETUP

			{ BEGIN(cpp_comment); }
			YY_BREAK
		case 57:
			/* rule 57 can match eol */
			YY_RULE_SETUP

			{ BEGIN(0); }
			YY_BREAK
		case 58:
			YY_RULE_SETUP

				; // skipped
			YY_BREAK
		case 59:
			YY_RULE_SETUP

			{ BEGIN(c_comment); }
			YY_BREAK
		case 60:
			YY_RULE_SETUP

			{ BEGIN(0); }
			YY_BREAK
		case 61:
			/* rule 61 can match eol */
			YY_RULE_SETUP

				; // skipped
			YY_BREAK
		case 62:
			YY_RULE_SETUP

				; // skipped
			YY_BREAK
		case 63:
			YY_RULE_SETUP

				return * yytext;
			YY_BREAK
		case 64:
			YY_RULE_SETUP

			{ yyerror("*** Unknown character '%c' (value 0x%x) ", *yytext, *yytext);}
			YY_BREAK
		case 65:
			YY_RULE_SETUP

				ECHO;
			YY_BREAK

		case YY_STATE_EOF(INITIAL):
		case YY_STATE_EOF(string_rules):
		case YY_STATE_EOF(file_line_rules):
		case YY_STATE_EOF(cpp_comment):
		case YY_STATE_EOF(c_comment):
			yyterminate();

		case YY_END_OF_BUFFER:
			{
				/* Amount of text matched not including the EOB char. */
				int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

				/* Undo the effects of YY_DO_BEFORE_ACTION. */
				*yy_cp = (yy_hold_char);
				YY_RESTORE_YY_MORE_OFFSET

					if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
					{
						/* We're scanning a new file or input source.  It's
						* possible that this happened because the user
						* just pointed yyin at a new source and called
						* yylex().  If so, then we have to assure
						* consistency between YY_CURRENT_BUFFER and our
						* globals.  Here is the right place to do so, because
						* this is the first action (other than possibly a
						* back-up) that will match for the new input source.
						*/
						(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
						YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
						YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
					}

					/* Note that here we test for yy_c_buf_p "<=" to the position
					* of the first EOB in the buffer, since yy_c_buf_p will
					* already have been incremented past the NUL character
					* (since all states make transitions on EOB to the
					* end-of-buffer state).  Contrast this with the test
					* in input().
					*/
					if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
					{ /* This was really a NUL. */
						yy_state_type yy_next_state;

						(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

						yy_current_state = yy_get_previous_state(  );

						/* Okay, we're now positioned to make the NUL
						* transition.  We couldn't have
						* yy_get_previous_state() go ahead and do it
						* for us because it doesn't know how to deal
						* with the possibility of jamming (and we don't
						* want to build jamming into it because then it
						* will run more slowly).
						*/

						yy_next_state = yy_try_NUL_trans( yy_current_state );

						yy_bp = (yytext_ptr) + YY_MORE_ADJ;

						if ( yy_next_state )
						{
							/* Consume the NUL. */
							yy_cp = ++(yy_c_buf_p);
							yy_current_state = yy_next_state;
							goto yy_match;
						}

						else
						{
							yy_cp = (yy_c_buf_p);
							goto yy_find_action;
						}
					}

					else switch ( yy_get_next_buffer(  ) )
					{
		case EOB_ACT_END_OF_FILE:
			{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
				{
					/* Note: because we've taken care in
					* yy_get_next_buffer() to have set up
					* yytext, we can now set up
					* yy_c_buf_p so that if some total
					* hoser (like flex itself) wants to
					* call the scanner after we return the
					* YY_NULL, it'll still work - another
					* YY_NULL will get returned.
					*/
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
				}

				else
				{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
				}
				break;
			}

		case EOB_ACT_CONTINUE_SCAN:
			(yy_c_buf_p) =
				(yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			yy_cp = (yy_c_buf_p);
			yy_bp = (yytext_ptr) + YY_MORE_ADJ;
			goto yy_match;

		case EOB_ACT_LAST_MATCH:
			(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

			yy_current_state = yy_get_previous_state(  );

			yy_cp = (yy_c_buf_p);
			yy_bp = (yytext_ptr) + YY_MORE_ADJ;
			goto yy_find_action;
					}
					break;
			}

		default:
			YY_FATAL_ERROR(
				"fatal flex scanner internal error--no action found" );
		} /* end of action switch */
	} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
*
* Returns a code representing an action:
*	EOB_ACT_LAST_MATCH -
*	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
*	EOB_ACT_END_OF_FILE - end of file
*/
static int yy_get_next_buffer (void)
{
	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
	{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
		{
			/* We matched a single character, the EOB, so
			* treat this as a final EOF.
			*/
			return EOB_ACT_END_OF_FILE;
		}

		else
		{
			/* We matched some text prior to the EOB, first
			* process it.
			*/
			return EOB_ACT_LAST_MATCH;
		}
	}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		* just force an EOF
		*/
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
	{
		size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
		{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
			{
				size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
			}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
				number_to_move - 1;

		}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (int) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
	}

	if ( (yy_n_chars) == 0 )
	{
		if ( number_to_move == YY_MORE_ADJ )
		{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
		}

		else
		{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
		}
	}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
	{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
		{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
		}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 199 )
				yy_c = yy_meta[(unsigned int) yy_c];
		}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
*
* synopsis
*	next_state = yy_try_NUL_trans( current_state );
*/
static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
	{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
	}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 199 )
			yy_c = yy_meta[(unsigned int) yy_c];
	}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 198);

	return yy_is_jam ? 0 : yy_current_state;
}

static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;

	yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
	{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
			register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

			while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
				*--dest = *--source;

			yy_cp += (int) (dest - source);
			yy_bp += (int) (dest - source);
			YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
				(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

			if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
				YY_FATAL_ERROR( "flex scanner push-back overflow" );
	}

	*--yy_cp = (char) c;

	if ( c == '\n' ){
		--yylineno;
	}

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput (void)
#else
static int input  (void)
#endif

{
	int c;

	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
	{
		/* yy_c_buf_p now points to the character we want to return.
		* If this occurs *before* the EOB characters, then it's a
		* valid NUL; if not, then we've hit the end of the buffer.
		*/
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
		{ /* need more input */
			int offset = (int)((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_LAST_MATCH:
				/* This happens because yy_g_n_b()
				* sees that we've accumulated a
				* token and flags that we need to
				* try matching the token before
				* proceeding.  But for input(),
				* there's no matching to consider.
				* So convert the EOB_ACT_LAST_MATCH
				* to EOB_ACT_END_OF_FILE.
				*/

				/* Reset buffer status. */
				yyrestart(yyin );

				/*FALLTHROUGH*/

			case EOB_ACT_END_OF_FILE:
				{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) = (yytext_ptr) + offset;
				break;
			}
		}
	}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )

		yylineno++;
	;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
* @param input_file A readable stream.
* 
* @note This function does not reset the start condition to @c INITIAL .
*/
void yyrestart  (FILE * input_file )
{

	if ( ! YY_CURRENT_BUFFER ){
		yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
			yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
* @param new_buffer The new input buffer.
* 
*/
void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{

	/* TODO. We should be able to replace this entire function body
	* with
	*		yypop_buffer_state();
	*		yypush_buffer_state(new_buffer);
	*/
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
	{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
	}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	* EOF (yywrap()) processing, but the only time this flag
	* is looked at is after yywrap() is called, so it's safe
	* to go ahead and always set it.
	*/
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
* @param file A readable stream.
* @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
* 
* @return the allocated buffer state.
*/
YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	* we need to put in 2 end-of-buffer characters.
	*/
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
* @param b a buffer created with yy_create_buffer()
* 
*/
void yy_delete_buffer (YY_BUFFER_STATE  b )
{

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */

/* Initializes or reinitializes a buffer.
* This function is sometimes called more than once on the same buffer,
* such as during a yyrestart() or at EOF.
*/
static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;

	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

	/* If b is the current buffer, then yy_init_buffer was _probably_
	* called from yyrestart() or through yy_get_next_buffer.
	* In that case, we don't want to reset the lineno or column.
	*/
	if (b != YY_CURRENT_BUFFER){
		b->yy_bs_lineno = 1;
		b->yy_bs_column = 0;
	}

	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;

	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
* @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
* 
*/
void yy_flush_buffer (YY_BUFFER_STATE  b )
{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	* a transition to the end-of-buffer state.  The second causes
	* a jam in that state.
	*/
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
*  the current state. This function will allocate the stack
*  if necessary.
*  @param new_buffer The new state.
*  
*/
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
	{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
	}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
*  The next element becomes the new top.
*  
*/
void yypop_buffer_state (void)
{
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
*  Guarantees space for at least one push.
*/
static void yyensure_buffer_stack (void)
{
	size_t num_to_alloc;

	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		* scanner will even need a stack. We use 2 instead of 1 to avoid an
		* immediate realloc on the next call.
		*/
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
			(num_to_alloc * sizeof(struct yy_buffer_state*)
			);

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
			((yy_buffer_stack),
			num_to_alloc * sizeof(struct yy_buffer_state*)
			);

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
* @param base the character buffer
* @param size the size in bytes of the character buffer
* 
* @return the newly allocated buffer state object. 
*/
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
		base[size-2] != YY_END_OF_BUFFER_CHAR ||
		base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
* scan from a @e copy of @a str.
* @param yystr a NUL-terminated string to scan
* 
* @return the newly allocated buffer state object.
* @note If you want to scan bytes that may contain NUL values, then use
*       yy_scan_bytes() instead.
*/
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{

	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
* scan from a @e copy of @a bytes.
* @param bytes the byte buffer to scan
* @param len the number of bytes in the buffer pointed to by @a bytes.
* 
* @return the newly allocated buffer state object.
*/
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	size_t i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	* away when we're done.
	*/
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
{ \
	/* Undo effects of setting up yytext. */ \
	int yyless_macro_arg = (n); \
	YY_LESS_LINENO(yyless_macro_arg);\
	yytext[yyleng] = (yy_hold_char); \
	(yy_c_buf_p) = yytext + yyless_macro_arg; \
	(yy_hold_char) = *(yy_c_buf_p); \
	*(yy_c_buf_p) = '\0'; \
	yyleng = yyless_macro_arg; \
} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
* 
*/
int yyget_lineno  (void)
{

	return yylineno;
}

/** Get the input stream.
* 
*/
FILE *yyget_in  (void)
{
	return yyin;
}

/** Get the output stream.
* 
*/
FILE *yyget_out  (void)
{
	return yyout;
}

/** Get the length of the current token.
* 
*/
int yyget_leng  (void)
{
	return yyleng;
}

/** Get the current token.
* 
*/

char *yyget_text  (void)
{
	return yytext;
}

/** Set the current line number.
* @param line_number
* 
*/
void yyset_lineno (int  line_number )
{

	yylineno = line_number;
}

/** Set the input stream. This does not discard the current
* input buffer.
* @param in_str A readable stream.
* 
* @see yy_switch_to_buffer
*/
void yyset_in (FILE *  in_str )
{
	yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
	yyout = out_str ;
}

int yyget_debug  (void)
{
	return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
	yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
	/* Initialization is the same as for the non-reentrant scanner.
	* This function is called from yylex_destroy(), so don't allocate here.
	*/

	/* We do not touch yylineno unless the option is enabled. */
	yylineno =  1;

	(yy_buffer_stack) = 0;
	(yy_buffer_stack_top) = 0;
	(yy_buffer_stack_max) = 0;
	(yy_c_buf_p) = (char *) 0;
	(yy_init) = 0;
	(yy_start) = 0;

	/* Defined in main.c */
#ifdef YY_STDINIT
	yyin = stdin;
	yyout = stdout;
#else
	yyin = (FILE *) 0;
	yyout = (FILE *) 0;
#endif

	/* For future reference: Set errno on error, since we are called by
	* yylex_init()
	*/
	return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{

	/* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

	/* Reset the globals. This is important in a non-reentrant scanner so the next time
	* yylex() is called, initialization will occur. */
	yy_init_globals( );

	return 0;
}

/*
* Internal utility routines.
*/

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	* implementations that use char* generic pointers, and those
	* that use void* generic pointers.  It works with the latter
	* because both ANSI C and C++ allow castless assignment from
	* any pointer type to void*, and deal with argument conversions
	* as though doing an assignment.
	*/
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"


