typedef unsigned int GLbitfield;
typedef short unsigned int GLushort;
typedef float GLfloat;
typedef int GLsizei;
typedef unsigned char GLubyte;
typedef signed char GLbyte;
typedef unsigned int GLenum;
typedef unsigned int GLuint;
typedef int GLintptrARB;
typedef int GLint;
typedef int GLfixed;
typedef float GLclampf;
typedef int GLclampx;
typedef int GLsizeiptrARB;
typedef void GLvoid;
typedef short int GLshort;
typedef MAAddress _GLfuncptr;
typedef unsigned char GLboolean;
void glAlphaFuncx(in GLenum func, in GLclampx ref);
void glFrontFace(in GLenum mode);
void glLoadIdentity();
void glTexImage2D(in GLenum target, in GLint level, in GLint internalformat, in GLsizei width, in GLsizei height, in GLint border, in GLenum format, in GLenum type, in MAAddress pixels);
void glGenTextures(in GLsizei n, out GLuint textures);
void glLogicOp(in GLenum opcode);
void glTexEnvf(in GLenum target, in GLenum pname, in GLfloat param);
void glTexEnvx(in GLenum target, in GLenum pname, in GLfixed param);
void glFlush();
void glStencilOp(in GLenum fail, in GLenum zfail, in GLenum zpass);
void glTexEnvxv(in GLenum target, in GLenum pname, in GLfixed* params);
void glPixelStorei(in GLenum pname, in GLint param);
void glFogxv(in GLenum pname, in GLfixed* params);
void glCullFace(in GLenum mode);
void glNormal3f(in GLfloat nx, in GLfloat ny, in GLfloat nz);
void glNormal3x(in GLfixed nx, in GLfixed ny, in GLfixed nz);
void glMultiTexCoord4f(in GLenum target, in GLfloat s, in GLfloat t, in GLfloat r, in GLfloat q);
void glMultiTexCoord4x(in GLenum target, in GLfixed s, in GLfixed t, in GLfixed r, in GLfixed q);
void glLightModelf(in GLenum pname, in GLfloat param);
void glLightModelx(in GLenum pname, in GLfixed param);
void glDepthRangef(in GLclampf zNear, in GLclampf zFar);
void glDepthRangex(in GLclampx zNear, in GLclampx zFar);
void glBindTexture(in GLenum target, in GLuint texture);
void glViewport(in GLint x, in GLint y, in GLsizei width, in GLsizei height);
void glLineWidthx(in GLfixed width);
void glGetIntegerv(in GLenum pname, out GLint params);
void glAlphaFunc(in GLenum func, in GLclampf ref);
void glLoadMatrixf(in GLfloat* m);
void glLoadMatrixx(in GLfixed* m);
void glTexEnvfv(in GLenum target, in GLenum pname, in GLfloat* params);
void glScissor(in GLint x, in GLint y, in GLsizei width, in GLsizei height);
void glFogfv(in GLenum pname, in GLfloat* params);
void glDrawArrays(in GLenum mode, in GLint first, in GLsizei count);
void glTexParameterf(in GLenum target, in GLenum pname, in GLfloat param);
void glTexParameterx(in GLenum target, in GLenum pname, in GLfixed param);
void glClearDepthf(in GLclampf depth);
void glClearDepthx(in GLclampx depth);
void glShadeModel(in GLenum mode);
void glTexSubImage2D(in GLenum target, in GLint level, in GLint xoffset, in GLint yoffset, in GLsizei width, in GLsizei height, in GLenum format, in GLenum type, in MAAddress pixels);
void glClientActiveTexture(in GLenum texture);
void glCopyTexImage2D(in GLenum target, in GLint level, in GLenum internalformat, in GLint x, in GLint y, in GLsizei width, in GLsizei height, in GLint border);
void glTexCoordPointer(in GLint size, in GLenum type, in GLsizei stride, in MAAddress pointer);
void glLightf(in GLenum light, in GLenum pname, in GLfloat param);
void glLightx(in GLenum light, in GLenum pname, in GLfixed param);
void glMaterialfv(in GLenum face, in GLenum pname, in GLfloat* params);
void glMultMatrixx(in GLfixed* m);
void glScalex(in GLfixed x, in GLfixed y, in GLfixed z);
void glDepthFunc(in GLenum func);
void glStencilFunc(in GLenum func, in GLint ref, in GLuint mask);
void glEnableClientState(in GLenum array);
void glFrustumf(in GLfloat left, in GLfloat right, in GLfloat bottom, in GLfloat top, in GLfloat zNear, in GLfloat zFar);
void glDepthMask(in GLboolean flag);
void glColor4f(in GLfloat red, in GLfloat green, in GLfloat blue, in GLfloat alpha);
void glStencilMask(in GLuint mask);
void glMatrixMode(in GLenum mode);
void glPolygonOffset(in GLfloat factor, in GLfloat units);
void glSampleCoverage(in GLclampf value, in GLboolean invert);
void glFrustumx(in GLfixed left, in GLfixed right, in GLfixed bottom, in GLfixed top, in GLfixed zNear, in GLfixed zFar);
void glMaterialxv(in GLenum face, in GLenum pname, in GLfixed* params);
void glCompressedTexSubImage2D(in GLenum target, in GLint level, in GLint xoffset, in GLint yoffset, in GLsizei width, in GLsizei height, in GLenum format, in GLsizei imageSize, in MAAddress data);
void glFogf(in GLenum pname, in GLfloat param);
void glFogx(in GLenum pname, in GLfixed param);
void glDrawElements(in GLenum mode, in GLsizei count, in GLenum type, in MAAddress indices);
void glDisableClientState(in GLenum array);
void glEnable(in GLenum cap);
void glMultMatrixf(in GLfloat* m);
void glFinish();
void glHint(in GLenum target, in GLenum mode);
void glNormalPointer(in GLenum type, in GLsizei stride, in MAAddress pointer);
void glScalef(in GLfloat x, in GLfloat y, in GLfloat z);
void glMaterialf(in GLenum face, in GLenum pname, in GLfloat param);
void glMaterialx(in GLenum face, in GLenum pname, in GLfixed param);
GLenum glGetError();
void glClearStencil(in GLint s);
void glClearColor(in GLclampf red, in GLclampf green, in GLclampf blue, in GLclampf alpha);
void glOrthof(in GLfloat left, in GLfloat right, in GLfloat bottom, in GLfloat top, in GLfloat zNear, in GLfloat zFar);
void glOrthox(in GLfixed left, in GLfixed right, in GLfixed bottom, in GLfixed top, in GLfixed zNear, in GLfixed zFar);
void glColorPointer(in GLint size, in GLenum type, in GLsizei stride, in MAAddress pointer);
void glColor4x(in GLfixed red, in GLfixed green, in GLfixed blue, in GLfixed alpha);
void glReadPixels(in GLint x, in GLint y, in GLsizei width, in GLsizei height, in GLenum format, in GLenum type, out MAAddress pixels);
void glColorMask(in GLboolean red, in GLboolean green, in GLboolean blue, in GLboolean alpha);
void glDisable(in GLenum cap);
void glClearColorx(in GLclampx red, in GLclampx green, in GLclampx blue, in GLclampx alpha);
void glVertexPointer(in GLint size, in GLenum type, in GLsizei stride, in MAAddress pointer);
void glPolygonOffsetx(in GLfixed factor, in GLfixed units);
void glPopMatrix();
void glSampleCoveragex(in GLclampx value, in GLboolean invert);
void glActiveTexture(in GLenum texture);
void glLightModelfv(in GLenum pname, in GLfloat* params);
void glClear(in GLbitfield mask);
void glTranslatex(in GLfixed x, in GLfixed y, in GLfixed z);
void glLightfv(in GLenum light, in GLenum pname, in GLfloat* params);
void glLightModelxv(in GLenum pname, in GLfixed* params);
void glLineWidth(in GLfloat width);
MAHandle glGetStringHandle(in GLenum name);
void glCompressedTexImage2D(in GLenum target, in GLint level, in GLenum internalformat, in GLsizei width, in GLsizei height, in GLint border, in GLsizei imageSize, in MAAddress data);
void glPushMatrix();
void glBlendFunc(in GLenum sfactor, in GLenum dfactor);
void glRotatef(in GLfloat angle, in GLfloat x, in GLfloat y, in GLfloat z);
void glRotatex(in GLfixed angle, in GLfixed x, in GLfixed y, in GLfixed z);
void glLightxv(in GLenum light, in GLenum pname, in GLfixed* params);
void glDeleteTextures(in GLsizei n, in GLuint* textures);
void glCopyTexSubImage2D(in GLenum target, in GLint level, in GLint xoffset, in GLint yoffset, in GLint x, in GLint y, in GLsizei width, in GLsizei height);
void glPointSize(in GLfloat size);
void glTranslatef(in GLfloat x, in GLfloat y, in GLfloat z);
void glPointSizex(in GLfixed size);
