// test1.h
// Generated by BitmapCompiler
// Copyright (c) 1998-2001 Symbian Ltd.  All rights reserved.
//

enum TMbmTest1
	{
	EMbmTest1Test1_48i,
	EMbmTest1Test1_48m,
	EMbmTest1Test1_32i,
	EMbmTest1Test1_32m,
	EMbmTest1Test1_24i,
	EMbmTest1Test1_24m,
	EMbmTest1Test1_16i,
	EMbmTest1Test1_16m
	};
