/*
Copyright (C) 2011 MoSync AB

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License,
version 2, as published by the Free Software Foundation.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
MA 02110-1301, USA.
*/

/**
 * @file WidgetManager.h
 * @author Mikael Kindborg
 *
 * The WidgetManager is the heart of the widget system
 * It has methods for creating widgets, and manages widget
 * events and dispatches them to the target widgets.
 */

#ifndef MOSYNC_UI_WIDGETMANAGER_H_
#define MOSYNC_UI_WIDGETMANAGER_H_

#include <ma.h>
#include <MAUtil/String.h>
#include <MAUtil/Map.h>
#include <MAUtil/Environment.h>
#include <IX_WIDGET.h>
#include "WidgetEventListener.h"
#include "Widget.h"
#include "Screen.h"
#include "Layout.h"
#include "TextWidget.h"
#include "Button.h"

namespace MoSync
{
	namespace UI
	{

	/**
	 * Class that manages widget creation and handles widget events.
	 */
	class WidgetManager : public MAUtil::CustomEventListener
	{
	public:
		/**
		 * Constructor.
		 */
		WidgetManager();

		/**
		 * Destructor.
		 */
		virtual ~WidgetManager();

		/**
		 * Create a screen widget.
		 * @return A screen widget.
		 */
		virtual Screen* createScreen();

		/**
		 * Create a horizontal layout. By default,
		 * this layout fills the parent space.
		 * @return An horizontal layout widget.
		 */
		virtual Layout* createHorizontalLayout();

		/**
		 * Create a vertical layout. By default,
		 * this layout fills the parent space.
		 * @return An vertical layout widget.
		 */
		virtual Layout* createVerticalLayout();

		/**
		 * Create a button widget.
		 * @return A button widget.
		 */
		virtual Button* createButton();

		/**
		 * Implementation of CustomEventListener interface.
		 * This method will get called whenever there is a
		 * widget event generated by the system.
		 */
		virtual void customEvent(const MAEvent& event);

	private:
		/**
		 * Error handling for devices that do not support NativeUI.
		 * Here we throw a panic if NativeUI is not supported.
		 */
		void checkNativeUISupport(int result);

		/**
		 * Add a widget to the map that holds widget objects.
		 */
		void addWidgetToMap(MAHandle widgetHandle, Widget* widget);

		/**
		 * Dictionary of widgets identified by widget handle.
		 */
		MAUtil::Map<MAHandle, Widget*> mWidgetMap;
	};

	} // namespace UI
} // namespace MoSync

#endif
