/*
Copyright (C) 2011 MoSync AB

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License,
version 2, as published by the Free Software Foundation.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
MA 02110-1301, USA.
*/

/**
 * @file WidgetManager.h
 * @author Mikael Kindborg
 *
 * The WidgetManager manages widget events and dispatches
 * them to the target widgets.
 */

#include "WidgetManager.h"

namespace MoSync
{
	namespace UI
	{

	/**
	 * Initialize the singleton variable to NULL.
	 */
	WidgetManager* WidgetManager::sInstance = NULL;


	/**
	 * Constructor.
	 */
	WidgetManager::WidgetManager()
	{
		// Add me as a custom event listener.
		MAUtil::Environment::getEnvironment().addCustomEventListener(this);
	}

	/**
	 * Destructor.
	 */
	WidgetManager::~WidgetManager()
	{
		// TODO: Do cleanup. Destroy widgets.
	}

	/**
	 * Return the single instance of this class.
	 */
	WidgetManager* WidgetManager::getInstance()
	{
		if (NULL == WidgetManager::sInstance)
		{
			WidgetManager::sInstance = new WidgetManager();
		}

		return sInstance;
	}

	/**
	 * Implementation of CustomEventListener interface.
	 * This method will get called whenever there is a
	 * widget event generated by the system.
	 */
	void WidgetManager::customEvent(const MAEvent& event)
	{
		// Check if this is a widget event.
		if (EVENT_TYPE_WIDGET == event.type)
		{
			// Get the widget event data structure.
			MAWidgetEventData* eventData = (MAWidgetEventData*) event.data;

			// Check if the widget exists in the map.
			if (mWidgetMap.end() != mWidgetMap.find(eventData->widgetHandle))
			{
				// Get the widget object that wraps the widget handle.
				Widget* widget = mWidgetMap[eventData->widgetHandle];

				// Call the widge's event handling method.
				widget->handleWidgetEvent(eventData);
			}
		}
	}

	/**
	 * Add a widget to the map that holds widgets.
	 */
	void WidgetManager::registerWidget(MAHandle widgetHandle, Widget* widget)
	{
		checkNativeUISupport(widgetHandle);
		mWidgetMap[widgetHandle] = widget;
	}

	/**
	 * Remove a widget from the map that holds widgets.
	 */
	void WidgetManager::unregisterWidget(MAHandle widgetHandle, Widget* widget)
	{
		mWidgetMap.erase(widgetHandle);
	}

	/**
	 * Error handling for devices that do not support NativeUI.
	 * Here we throw a panic if NativeUI is not supported.
	 */
	void WidgetManager::checkNativeUISupport(int result)
	{
		if (-1 == result)
		{
			maPanic(0,
				"NativeUI is only available on Android and iPhone. "
				"You must run directly on the device or devices emulator.");
		}
	}

	} // namespace UI
} // namespace MoSync
