Document: makesis
Title: Debian makesis Manual
Author: <insert document author here>
Abstract: This manual describes what makesis is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/makesis/makesis.sgml.gz

Format: postscript
Files: /usr/share/doc/makesis/makesis.ps.gz

Format: text
Files: /usr/share/doc/makesis/makesis.text.gz

Format: HTML
Index: /usr/share/doc/makesis/html/index.html
Files: /usr/share/doc/makesis/html/*.html

  
