.TH LCAB "1" "August 2003" "lcab 1.0b8"
.SH NAME
lcab \- Create cabinet (.cab) files.
.SH SYNOPSIS
.B lcab
[\fIOPTION\fR]... \fISOURCE\fR... \fICABFILE\fR
.SH DESCRIPTION
.PP
Create the cabinet file CABFILE from the SOURCE files. SOURCE files
can also be directories when the \fB\-r\fR option is specified.
.SH OPTIONS
.TP
\fB\-r\fR
loop recursively through directories
.TP
\fB\-n\fR
create files without pathnames
.TP
\fB\-q\fR
be quiet!
.SH AUTHOR
Written by Rien <rien@geekshop.be>.

This manual page was written by Shaun Jackman <sjackman@debian.org>
for the Debian GNU/Linux system.

.SH "SEE ALSO"
http://www.geekshop.be/rien/lcab/
