group ActionBarErrorCodes "Action Bar Error Codes" {
	constset int MAW_RES_ACTION_BAR_{
		/**
		* Indicates that the #maActionBarAddMenuItem() or #maActionBarSetIcon() calls failed because they pointed to an invalid icon,
		*/
		INVALID_ICON = -1;
		/**
		* Indicates that the #maActionBarAddMenuItem() call failed because the displayFlag was invalid.
		*/
		INVALID_FLAG = -2;
		/**
		* Indicates that an action bar related syscall failed because the platform does not support it.
		*/
		NOT_AVAILABLE = -3;
		/**
		* Indicates that an action bar related syscall failed because it is not enabled.
		*/
		DISABLED = -4;
	}
} // end of group ActionBarErrorCodes

/**
* Sets how an item should display in the presence of an Action Bar.
*/
group ActionBarItemDisplayFlag "Action Bar Item Display Flag" {
	constset int MAW_ACTION_BAR_ITEM_SHOW_ {
		/**
		* Show this item as a button in an Action Bar if the system decides there is room for it.
		*/
		IF_ROOM = 1;
		/**
		* Always show this item as a button in an Action Bar.
		* Use sparingly! If too many items are set to always show in the Action Bar it can crowd it
		* and degrade the user experience on devices with smaller screens.
		* A good rule of thumb is to have no more than 2 items set to always show at a time.
		*/
		ALWAYS = 2;
		/**
		* When this item is in the action bar, always show it with a text label even if it also has an icon specified.
		*/
		WITH_TEXT = 4;
		/**
		* This item's action view collapses to a normal menu item.
		* When expanded, the action view temporarily takes over a larger segment of its container.
		*/
		COLLAPSE_ACTION_VIEW = 8;
	}
} // end of group ActionBarItemDisplayFlag
