
/**
* The set of functions available for the Action Bar. Available only on Android.
*/
group ActionBarFunctions "Action Bar functions" {

	/**
	* Android specific .. TODO test with tab screens
	* The ActionBar is unique per application, therefore all syscalls that relate to the Action Bar will be handled on that unique instance.
	* Available only on Android.
	* @param iconPredefinedId optional icon for the action bar item.
	*/
	MAHandle maActionBarAddMenuItem(in MAString title, in int iconPredefinedId, in int displayFlag);

	int maActionBarGetHeight();

	int maActionBarRemove();

	int maActionBarRemoveItem(in MAHandle itemHandle);

	/**
	* Returns true if the ActionBar is showing, false otherwise.
	*/
	bool maActionBarIsShowing();

	/**
	* Enable or disable the display of the action bar.
	* The Action Bar is always disabled by default.
	*/
	int maActionBarEnableShow(in bool showActionBar);

	/**
	* Set the ActionBar's background. This will be used for the primary action bar.
	*/
	int maActionBarSetBackgroundDrawable(in MAHandle imageHandle);
	int maActionBarSetBackgroundDrawable(in MAString imagePath);
	int maActionBarSetIcon(in MAHandle logoHandle); //setLogo
	int maActionBarEnableSplit(in bool enableSplit);

	/**
	* To enable the icon for up navigation (which displays the "up" indicator next to the icon), call setDisplayHomeAsUpEnabled(true) on your ActionBar.
	* false is the default value.
	*/
	int maActionBarSetDisplayHomeAsUpEnabled(in bool set);

	/**
	*
	*/
	int maActionBarShowTitleEnabled(bool showTitle);

	/**
	* If you're using the icon to navigate to the home activity, beware that beginning with Android 4.0 (API level 14),
	* you must explicitly enable the icon as an action item by calling setHomeButtonEnabled(true)
	* (in previous versions, the icon was enabled as an action item by default).
	*/
	int maActionBarSetHomeButtonEnabled(in bool state);

} // end of group ActionBarFunctions
