/**
* The available widget properties for a #MAW_LIST_VIEW_SECTION.
*/
group WidgetListViewSectionProperties "List View Section" {
	constset MAString MAW_LIST_VIEW_SECTION_ {
		/**
		* @brief Set or get section title.
		* Section title will appear on the right side of the list.
		*
		* Platform: iOS.
		*
		* @validvalue A string.
		*
		* @setandget
		*
		* @par Example
		* \code
		*	maWidgetSetProperty(listSectionHandle, MAW_LIST_VIEW_SECTION_TITLE, "A");
		* \endcode
		*/
		TITLE = "title";

		/**
		* @brief Set or get section header text.
		* Section text will appear above the section items.
		*
		* Platform: iOS.
		*
		* @validvalue A string.
		*
		* @setandget
		*
		* @par Example
		* \code
		*	maWidgetSetProperty(listSectionHandle, MAW_LIST_VIEW_SECTION_HEADER, "Header text");
		* \endcode
		*/
		HEADER = "header";

		/**
		* @brief Set or get section footer text.
		* Section text will appear below the section items.
		*
		* Platform: iOS.
		*
		* @validvalue A string.
		*
		* @setandget
		*
		* @par Example
		* \code
		*	maWidgetSetProperty(listSectionHandle, MAW_LIST_VIEW_SECTION_FOOTER, "Footer text");
		* \endcode
		*/
		FOOTER = "footer";
	}
} // end of WidgetSegmentedListViewSectionProperties
